server {
    listen 80;
    server_name learnforgelab.com;

    # Let's Encryptのドメイン所有確認用
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Spring Boot
    location / {
        proxy_pass http://app:8080;
    }
}
